# Generated by Django 3.2.25 on 2024-12-22 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('wh_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('wh_name', models.CharField(max_length=100)),
                ('wh_comment', models.CharField(blank=True, max_length=500)),
                ('wh_bg', models.CharField(blank=True, max_length=50)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2024, 12, 22, 5, 1, 20, 761738, tzinfo=utc))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2024, 12, 22, 5, 1, 20, 761738, tzinfo=utc))),
                ('create_by', models.DateTimeField(null=True)),
            ],
        ),
    ]
