# Generated by Django 3.2.25 on 2024-12-22 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='update_by',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 5, 1, 46, 423613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 5, 1, 46, 423613, tzinfo=utc)),
        ),
    ]
