# Generated by Django 3.2.25 on 2024-12-22 05:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20241222_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 5, 46, 49, 655318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 5, 46, 49, 655318, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2024, 12, 22, 5, 46, 49, 655318, tzinfo=utc))),
                ('create_by', models.DateTimeField(null=True)),
                ('update_at', models.DateTimeField(default=datetime.datetime(2024, 12, 22, 5, 46, 49, 655318, tzinfo=utc))),
                ('update_by', models.DateTimeField(null=True)),
                ('wh_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
    ]
