# Generated by Django 3.2.25 on 2024-12-22 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20241222_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attr_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('attr_name', models.CharField(max_length=50)),
                ('update_at', models.DateTimeField(default=datetime.datetime(2024, 12, 22, 6, 8, 23, 388259, tzinfo=utc))),
                ('update_by', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='area',
            old_name='wh_code',
            new_name='warehouse',
        ),
        migrations.AlterField(
            model_name='area',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 6, 8, 23, 388259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='area',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 6, 8, 23, 388259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 6, 8, 23, 388259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 6, 8, 23, 388259, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bin_name', models.CharField(max_length=100)),
                ('pos_x', models.IntegerField(blank=True)),
                ('pos_y', models.IntegerField(blank=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2024, 12, 22, 6, 8, 23, 388259, tzinfo=utc))),
                ('create_by', models.DateTimeField(null=True)),
                ('update_at', models.DateTimeField(default=datetime.datetime(2024, 12, 22, 6, 8, 23, 388259, tzinfo=utc))),
                ('update_by', models.DateTimeField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.area')),
            ],
        ),
    ]
