# Generated by Django 3.2.25 on 2024-12-22 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20241222_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin_Attr_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.DateTimeField(null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.attribute')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.bin')),
            ],
        ),
    ]
